--- #YAML:1.0
name:               Directory-Iterator-XS
version:            1.001002
abstract:           Recursive directory listing, fast XS backend
author:
    - Steve Sanbeg <sanbeg@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    repository:  https://github.com/sanbeg/Directory-Iterator
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
