---
abstract: 'Recursively list file contents'
author:
  - 'Steve Sanbeg'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Directory-Iterator-XS
no_index:
  directory:
    - t
    - inc
requires: {}
version: 1.000001
